import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

// Fix the typo here: change Monserrat to Montserrat
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stay Predictor App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
